#!/bin/bash
#
#	#### Secopx Sensor Test File #### 
# version: 1.0 # author: Gil Stolar # copytight 2021 Secopx LTD
#
#		## IMPORTANT! ##
# First check the feature you have tempered with INDIVIDUALLY !
# Then run a complete test with '--all' flag.
#
. /opt/IntruSense-v30/secopx.conf
printf "\nWEBSERVER_DIR:${WEBSERVER_DIR}\n"
WORKDIR=$(pwd)
SENSORDIR="/opt/IntruSense-v30"
IP=$(hostname -I | awk '{print $1}')
DIST=$(cat /etc/*-release | head -n 1)
MODS_DIR="/etc/apache2/mods-enabled" # Default apache2 path
if [[ ${DIST} == "*Amazon*" || ${DIST} == "*CentOS*" ]];then MODS_DIR="/etc/httpd/"; fi
#PKG_WITH_KNOWNCVE=""
#OUTDATED_PKG_LIST=""
#NOT TESTED :: ModSecurity Outdated CVE 
# AIDE will be tested when any file is being created on the web server directory
help_txt="
Run all tests with:     --all           
Or 
Run selective tests:
                        --chkrootkit
                        --yara
                        --webshells
                        --coinscan
                        --predictor
                        --btmp
                        --scalp
                        --dos
                        --cve
                        --outdated

Add one of the options:
                        -c      Creaet test files
                        -d      Delete test files
"

### Initialize test ###
systemctl stop secopx
#rm /opt/IntruSense-v30/tmp/*


### Set testing files on the machine file system ###
if [[  "${1}" == "--help" || "${1}" == "-h" || $# -lt 2 || ! " $@ " =~ " -c " && ! " $@ " =~ " -d " ]];then echo "${help_txt}";exit 0;fi
if [[ " $@ " =~ " -c " ]];then printf "Creating test files on ${IP},\n";fi
if [[ " $@ " =~ " -d " ]];then printf "Deleting test files from ${IP}.\n";fi

if [[ " $@ " =~ " --chkrootkit " || " $@ " =~ " --all " ]];then
        if [[ " $@ " =~ " -c " ]];then touch /tmp/ramen.tgz;DPS="--deepscan";
	elif [[ " $@ " =~ " -d " ]];then rm /tmp/ramen.tgz; fi
fi

if [[  " $@ " =~ " --yara " || " $@ " =~ " --all " ]];then
        if [[ " $@ " =~ " -c " ]];then 	cp zadon/RAASNet.py ${WEBSERVER_DIR}/RASSNet.py;
        elif [[ " $@ " =~ " -d " ]];then rm ${WEBSERVER_DIR}/RASSNet.py; fi
fi

if [[ " $@ " =~ " --webshells " || " $@ " =~ " --all " ]];then
        if [[ " $@ " =~ " -c " ]];then cp ${WORKDIR}/zadon/c99.php ${WEBSERVER_DIR}/c99.php;
        elif [[ " $@ " =~ " -d " ]];then rm ${WEBSERVER_DIR}/c99.php; fi
fi

if [[ " $@ " =~ " --coinscan " || " $@ " =~ " --all " ]];then
        if [[ " $@ " =~ " -c " ]];then cp ${WORKDIR}/zadon/miner.js ${WEBSERVER_DIR}/miner.js;
        elif [[ " $@ " =~ " -d " ]];then rm ${WEBSERVER_DIR}/miner.js; fi
fi

if [[ " $@ " =~ " --predictor " || " $@ " =~ " --all " ]];then
        if [[ " $@ " =~ " -c " ]];then cp ${WORKDIR}/zadon/ajaxshell.php ${WEBSERVER_DIR}/ajaxshell.php; DPS="--deepscan"
        elif [[ " $@ " =~ " -d " ]];then rm ${WEBSERVER_DIR}/ajaxshell.php; fi
fi

if [[ " $@ " =~ " --relay " || " $@ " =~ " --all " ]];then
        if [[ " $@ " =~ " -c " ]];then sed -i -e '1s/^/ProxyRequests On/' ${MODS_DIR}/mime.conf;
        elif [[ " $@ " =~ " -d " ]];then sed -i -e '1s/ProxyRequests On//' ${MODS_DIR}/mime.conf; fi
fi

if [[ " $@ " =~ " --btmp " || " $@ " =~ " --all " ]];then
        if [[ " $@ " =~ " -c " ]];then mv /var/log/btmp /var/log/btmp.bak; fallocate -l 500MB /var/log/btmp;
	elif [[ " $@ " =~ " -d " ]];then mv /var/log/btmp.bak /var/log/btmp; fi
fi

if [[ " $@ " =~ " -c " ]];then
	if [[ " $@ " =~ " --scalp " || " $@ " =~ " --all " ]];then
        	i=0
        	while [ $i -lt 5 ]; do curl "http://${IP}:8000/%22GET%20/?a=fetch&content=die(@md5(HelloThinkCMF))"; let "i+=1"; done
	fi

	if [[ " $@ " =~ " --dos " || " $@ " =~ " --all " ]];then
		i=0
        	while [ $i -lt 50 ]; do curl  "http://${IP}/%22GET%20/?a=fetch&content=die(@md5(HelloThinkCMF))"; let "i+=1"; done
	fi
fi

# to perform this tests need to add lists of old pakages with CVE  
#if [[ " $@ " =~ " --cve " || " $@ " =~ " --all " ]];then
#	if [[ " $@ " =~ " -c " ]];then
#		if [[ "$DIST" == *"CentOS"* ]]; then yum install $PKG_WITH_KNOWN_CVE; else apt-get install $PKG_WITH_KNOWN_CVE;	fi
#	elif [[ " $@ " =~ " -d " ]];then 
#		if [[ "$DIST" == *"CentOS"* ]]; then yum remove $PKG_WITH_KNOWN_CVE; else apt-get remove $PKG_WITH_KNOWN_CVE; fi
#	fi
#fi
#if [[ " $@ " =~ " --outdated " || " $@ " =~ " --all " ]];then
#        if [[ " $@ " =~ " -c " ]];then
#                if [[ "$DIST" == *"CentOS"* ]]; then yum install $OUTDATED_PKG_LIST; else apt-get install $OUTDATED_PKG_LIST; fi
#        elif [[ ${2} == "-d" ]];then
#                if [[ "$DIST" == *"CentOS"* ]]; then yum remove $OUTDATED_PKG_LIST; else apt-get remove $OUTDATED_PKG_LIST; fi
#        fi
#fi


if [[ " $@ " =~ " -d " ]];then exit 0;fi

### Run secopx-sensor and check result ###
cd ${SENSORDIR}; ./secopx --local-report ${DPS}

## Check scan results ###
cd ${WORKDIR}; python2 check-xml.py "${@}"

